[0m20:37:08.263598 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EBEBAFA3C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EBECAE9450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EBECAE9590>]}


============================== 20:37:08.272076 | eeb59c6f-e250-4ebb-a8f7-4ea578177c5e ==============================
[0m20:37:08.272076 [info ] [MainThread]: Running with dbt=1.9.2
[0m20:37:08.272577 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Janice Gleice Melo\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt seed', 'send_anonymous_usage_stats': 'True'}
[0m20:37:08.273115 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Janice Gleice Melo\Desktop\janice\teste-prefeitura\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:37:08.273778 [debug] [MainThread]: Command `dbt seed` failed at 20:37:08.273680 after 0.12 seconds
[0m20:37:08.274038 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EBECC890F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EBECB52F90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EBECB31E10>]}
[0m20:37:08.274301 [debug] [MainThread]: Flushing usage events
[0m20:37:08.936010 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m21:55:44.317058 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000246B660E120>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000246B47B9310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000246B778BD90>]}


============================== 21:55:44.328675 | 3e2804d2-bd6b-4281-b84d-62db16788f47 ==============================
[0m21:55:44.328675 [info ] [MainThread]: Running with dbt=1.9.2
[0m21:55:44.329692 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Janice Gleice Melo\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt seed', 'send_anonymous_usage_stats': 'True'}
[0m21:55:44.330172 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Janice Gleice Melo\Desktop\janice\teste-prefeitura\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:55:44.331896 [debug] [MainThread]: Command `dbt seed` failed at 21:55:44.331762 after 0.21 seconds
[0m21:55:44.332249 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000246B77A90F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000246B766EF90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000246B764DE10>]}
[0m21:55:44.332683 [debug] [MainThread]: Flushing usage events
[0m21:55:44.395045 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m21:59:28.883128 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025F4627E120>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025F44419310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025F473EBD90>]}


============================== 21:59:28.890886 | d6be335b-3491-4ec9-ad7c-4563bbfe1c27 ==============================
[0m21:59:28.890886 [info ] [MainThread]: Running with dbt=1.9.2
[0m21:59:28.891927 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\Janice Gleice Melo\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt seed', 'send_anonymous_usage_stats': 'True'}
[0m21:59:28.892317 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Janice Gleice Melo\Desktop\janice\teste-prefeitura\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:59:28.893900 [debug] [MainThread]: Command `dbt seed` failed at 21:59:28.893791 after 0.11 seconds
[0m21:59:28.894185 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025F474090F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025F472D2F90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025F472ADE10>]}
[0m21:59:28.894477 [debug] [MainThread]: Flushing usage events
[0m21:59:29.549950 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:00:30.095246 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020D6BADE120>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020D69C89310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020D6CC4BD90>]}


============================== 22:00:30.104838 | ed4e597e-00cd-40ca-8dcf-c4b30da0d032 ==============================
[0m22:00:30.104838 [info ] [MainThread]: Running with dbt=1.9.2
[0m22:00:30.105921 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Janice Gleice Melo\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt seed', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:00:30.106435 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Janice Gleice Melo\Desktop\janice\teste-prefeitura\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:00:30.108213 [debug] [MainThread]: Command `dbt seed` failed at 22:00:30.108083 after 0.14 seconds
[0m22:00:30.108563 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020D6CC690F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020D6CB32F90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020D6CB0DE10>]}
[0m22:00:30.108907 [debug] [MainThread]: Flushing usage events
[0m22:00:30.213193 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:00:40.789570 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020E98B6E120>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020E96D09310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020E99CCBD90>]}


============================== 22:00:40.797810 | 12a61009-9de8-470c-8044-379f6148873d ==============================
[0m22:00:40.797810 [info ] [MainThread]: Running with dbt=1.9.2
[0m22:00:40.798800 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Janice Gleice Melo\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt seed', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:00:40.799232 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Janice Gleice Melo\Desktop\janice\teste-prefeitura\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:00:40.800957 [debug] [MainThread]: Command `dbt seed` failed at 22:00:40.800783 after 0.13 seconds
[0m22:00:40.801445 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020E99CE90F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020E99BAEF90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020E99B8DE10>]}
[0m22:00:40.801969 [debug] [MainThread]: Flushing usage events
[0m22:00:40.865138 [debug] [MainThread]: An error was encountered while trying to flush usage events
